(() => {
  "use strict";
  Object.defineProperty(window, "RMLSetupTemplateMarkup", {
    value: "<!-- Lazy-loaded by setup_assistant.js. -->\n<div id=\"rml-setup-assistant\" hidden aria-live=\"polite\">\n  <div class=\"rml-setup-shade\" data-setup-shade=\"top\"></div>\n  <div class=\"rml-setup-shade\" data-setup-shade=\"left\"></div>\n  <div class=\"rml-setup-shade\" data-setup-shade=\"right\"></div>\n  <div class=\"rml-setup-shade\" data-setup-shade=\"bottom\"></div>\n\n  <svg class=\"rml-setup-demo-wire-layer\" aria-hidden=\"true\">\n    <path data-setup-demo-wire hidden></path>\n    <path data-setup-demo-wire-secondary hidden></path>\n    <path data-setup-demo-wire-tertiary hidden></path>\n  </svg>\n  <div class=\"rml-setup-demo-crossing\" data-setup-demo-crossing hidden aria-hidden=\"true\"></div>\n  <div class=\"rml-setup-demo-keys\" data-setup-demo-keys hidden aria-hidden=\"true\"></div>\n  <div class=\"rml-setup-drag-ghost\" data-setup-drag-ghost hidden aria-hidden=\"true\"></div>\n  <div class=\"rml-setup-demo-label\" data-setup-demo-label hidden aria-hidden=\"true\"></div>\n  <div class=\"rml-setup-demo-mouse\" data-setup-mouse aria-hidden=\"true\">\n    <svg viewBox=\"0 0 46 62\">\n      <path class=\"rml-setup-mouse-body\" d=\"M23 2C12.5 2 5 10.3 5 21v18c0 11.2 7.4 20 18 20s18-8.8 18-20V21C41 10.3 33.5 2 23 2Z\"></path>\n      <path class=\"rml-setup-mouse-split\" d=\"M23 3v22\"></path>\n      <rect data-setup-mouse-wheel x=\"20\" y=\"9\" width=\"6\" height=\"12\" rx=\"3\"></rect>\n    </svg>\n    <span class=\"rml-setup-mouse-ripple\"></span>\n  </div>\n\n  <section class=\"rml-setup-card\" role=\"dialog\" aria-modal=\"true\" aria-labelledby=\"rml-setup-title\">\n    <small data-setup-kicker>Interactive live tour</small>\n    <h2 id=\"rml-setup-title\" data-setup-title>Welcome</h2>\n    <p data-setup-text></p>\n    <span class=\"rml-setup-step-badge\" data-setup-hint></span>\n    <div class=\"rml-setup-progress\"><span data-setup-progress></span></div>\n    <div class=\"rml-setup-actions\">\n      <button class=\"button secondary\" type=\"button\" data-setup-skip>Skip tour</button>\n      <div>\n        <button class=\"button secondary\" type=\"button\" data-setup-back>Back</button>\n        <button class=\"button primary\" type=\"button\" data-setup-next>Next</button>\n      </div>\n    </div>\n  </section>\n</div>\n",
    writable: false,
    enumerable: false,
    configurable: true
  });
})();
